[package]
name = "straw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
console = "0.15.8"
crossterm = "0.27.0"
walkdir = "2.5.0"
